-- Esvaziada em 2026-09-07, por decisão do dono. Nada a aplicar.
--
-- Criava o job de cron `check-alerts-hourly` apontando para o projeto antigo
-- do Lovable (csbhhvgnbpleinxlpkcd), com a chave `anon` dele escrita aqui
-- dentro. No test-helpoint o job foi reescrito à mão em 2026-09-03 (URL do
-- projeto certo, chave lida do vault) e nenhuma migration registrava isso —
-- uma base nova nasceria com o robô chamando o projeto errado.
--
-- Além disso, `pg_cron` era ligado pelo painel: numa base do zero (CI) esta
-- migration quebrava em `relation "cron.job" does not exist`.
--
-- O job passa a ser definido por `20260907010000_cron_jobs_via_vault.sql`,
-- com extensões idempotentes e URL + chave lidos do vault. O histórico da
-- Supabase compara versão, não conteúdo: onde esta já rodou, nada muda.
